- name: Install AWS CLI on master
  hosts: master
  become: true

  tasks:
    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Download AWS CLI v2 zip
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI v2 installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Run AWS CLI installer
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Check AWS CLI version
      command: aws --version
      register: aws_version

    - name: Show AWS CLI version
      debug:
        msg: "{{ aws_version.stdout }}"
