# Step 1: Create EKS cluster in 1a and 1b
eksctl create cluster \
  --name=wanderlust \
  --region=ap-south-1 \
  --version=1.33 \
  --zones=ap-south-1a,ap-south-1b \
  --without-nodegroup

# Step 2: Associate IAM OIDC provider
eksctl utils associate-iam-oidc-provider \
  --region ap-south-1 \
  --cluster wanderlust \
  --approve

# Step 3: Create node group across 1a and 1b (autoscaling = off, fixed 2 nodes)
eksctl create nodegroup \
  --cluster=wanderlust \
  --region=ap-south-1 \
  --name=wanderlust \
  --node-type=t2.large \
  --nodes=2 \
  --nodes-min=2 \
  --nodes-max=2 \
  --node-volume-size=29 \
  --node-zones=ap-south-1a,ap-south-1b \
  --ssh-access \
  --ssh-public-key=eks-nodegroup-key
