- name: Install and configure SonarQube on Master
  hosts: master
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run SonarQube container
      community.docker.docker_container:
        name: SonarQube-Server
        image: sonarqube:lts-community
        state: started
        restart_policy: unless-stopped
        ports:
          - "9000:9000"

- name: Install Trivy on master
  hosts: master
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Trivy GPG key
      apt_key:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present

    - name: Add Trivy repo to sources list
      apt_repository:
        repo: "deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_lsb.codename }} main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Trivy
      apt:
        name: trivy
        state: present
