- name: Install Docker CE and run SonarQube
  hosts: master
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run SonarQube container
      community.docker.docker_container:
        name: SonarQube-Server
        image: sonarqube:lts-community
        state: started
        restart_policy: unless-stopped
        ports:
          - "9000:9000"

- name: Install Trivy
  hosts: master
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Trivy GPG key
      apt_key:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present

    - name: Add Trivy APT repository
      apt_repository:
        repo: "deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_lsb.codename }} main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Trivy
      apt:
        name: trivy
        state: present
